### ISSUE TITLE
Decide on default headers for each area of Ghost

### ISSUE THREAD

**Issue by tuijapalovuori** [dmitrymarokhonov/Ghost#7]
See https://github.com/TryGhost/Ghost/issues/11084 for details.

**Comment by Asbah-Usmani** [comment]
There are many different headers that can be used to improve security. These headers can be set by following these instructions:  [ https://www.netlify.com/docs/headers-and-basic-auth/].

Headers:
  Referrer-Policy: no-referrer-when-downgrade
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  Content-Security-Policy: default-src 'self'
  Cache-Control: no-store
  Clear-Site-Data: "*"
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-Xss-Protection:	1; mode=block
  Feature-Policy: accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'
